version: '3'

services:
  delivery-app-server:
    build:
      context: .
      dockerfile: Dockerfile
    image: delivery-app-server:latest
    ports:
      - "8080:8080"
    depends_on:
      - mongodb
    links:
      - mongodb
    networks:
      - delivery-network
    volumes:
      - images-vol:/app/images

  mongodb:
    container_name: mongodb
    image: mongodb/mongodb-community-server:6.0-ubi8
    environment:
      - MONGO_INITDB_ROOT_USERNAME=user123
      - MONGO_INITDB_ROOT_PASSWORD=123456
    ports:
      - "27017:27017"
    volumes:
      - type: bind
        source: docker-dev/database/data
        target: /data/db
    networks:
      - delivery-network

  redis:
    image: redis:latest
    command: redis-server
    volumes:
      - redis:/var/lib/redis
      - redis-config:/usr/local/etc/redis/redis.conf
    ports:
      - "6379:6379"
    networks:
      - delivery-network

  redis-commander:
    image: rediscommander/redis-commander:latest
    environment:
      - REDIS_HOSTS=local:redis:6379
      - HTTP_USER=root
      - HTTP_PASSWORD=123456
    ports:
      - "8081:8081"
    networks:
      - delivery-network
    depends_on:
      - redis


volumes:
  database-vol:
  images-vol:
  redis:
  redis-config:

networks:
  delivery-network:
    driver: bridge
