#hide on mongo container using docker exect -it <container_id> mongosh -u user -p password
#create a database devdelivery
#use database with comand: use devdelivery;
#after should create a user for this application usign this comand: db.createUser({user: "testUser", pwd: "123", roles: [{role: "readWrite", db: "*"}]})
#after you should be quit bash of container using: ctrl + p + q

version: '3'

services:
  mongodb:
    container_name: mongodb-1
    image: mongodb/mongodb-community-server:6.0-ubi8
    environment:
      - MONGO_INITDB_ROOT_USERNAME=user123
      - MONGO_INITDB_ROOT_PASSWORD=123456
    ports:
      - "27017:27017"
    volumes:
      - type: bind
        source: ./data
        target: /data/db